### ISSUE TITLE
Possibly make hunks and lines public for more extensible analysis.

### ISSUE THREAD

**Issue by kgalang** [messense/unidiff-rs#4]
Hello! Out of curiosity, would it be reasonable to make `PatchedFile.hunks` and `Hunk.lines` properties public? I can make the PR for it too if it sounds ok but just wanted to discuss if you had any particular thoughts on why they should or shouldn't be private.

In one of my use cases, I'd like to go through each hunk and see if the added lines included comment lines. I appreciate your work here and would like to use it to avoid rewriting all of the core diff parsing.

If this is something you wouldn't like to do, please let me know and I can just work off of your code or fork.

Thank you!

**Comment by kgalang** [comment]
Sorry. Just re-read the source code some more and saw I can access these through iter.

**Comment by messense** [comment]
Added some simple help methods in v0.3.3. https://github.com/messense/unidiff-rs/commit/844ef406879b5c2d8947e572d3248a2ca6a9379f
